#station is highest index
0:
  acdc_id: 55
  lappd_id: 128
  z_position: 0 #meters, finely calibrated
  active: 1

1:
  acdc_id: 58
  lappd_id: 125
  z_position: 10 
  active: 1

2:
  acdc_id: 62
  lappd_id: 51
  z_position: 30 
  active: 1

3:
  acdc_id: 66
  lappd_id: 43
  z_position: 40 
  active: 1
