acdc_id: 62
lappd_id: 157
acc_id: 1
station_id: 2
sync_ch: 5
zpos: 3.21
corner_offset: [0, 0]
pedestal_file_name: 'testData/ped_Raw_testData_ACC1_20230714_093238_b0.txt'
calib_file_name: 'calib/acdc62.root'