calibration_file: configs/0/test.h5 #A calibration file to save measurement results. You may override existing calibration.
tasks: r #r: raw data, p: linearized plot, v: voltage curve, t:timebase, j:phase jittering calculation
plot:
  event: 20
  pedestal: 0x800
  input: testData/EJ_WR_5way_3
voltage_curve:
  start: 0x000
  step: 0x010
  end: 0xfff
  prefix: configs/0/scan_pedestals_ #configs/0/Raw_testData_scan_pedestals_
  suffix: "" #_20220817_052515_b0.txt

timebase:
  channels: [11, 17, 23, 29]
  nevents: 1000
  true_freq: 250000000 #243184495 #True frequency of the sine wave source.
  pedestal: 0x800 #Pedestal voltage during measurement.
  input: testData/EJ_WR_5way_3