calibration_file: configs/0/acdc60.root #A calibration file to save measurement results. You may override existing calibration.
#V: vervose
tasks: h 
#r: raw data, p: linearized plot, v: voltage curve, t:timebase, T:timebase first order 
#j:phase jittering calculation, l: first order timebase correction
#w: weighted timebase correction, h: draw ellipse plots, R: wraparound only
#E: Add errorbar
plot:
  event: [200, 300, 400, 500, 600, 700, 800, 900]
  pedestal: 0xb00
  input: acdc60/Raw_testData_ACC1_20240403_162735_b0_dll0x300.txt
voltage_curve:
  start: 0x000
  step: 0x010
  end: 0xfff
  prefix: configs/0/scan_pedestals_ #configs/133741/Raw_CounterTest_scan_pedestals_ ##Final file name: prefix_(pedvalue in decimal)_suffix
  suffix: "" #"_20230927_133741_b1.txt"

timebase:
  channels: [5]#channels to be used for timebase calculation
  nevents: 10000
  true_freq: 250000000 #243184495 #True frequency of the sine wave source.
  binsize: 5000
  pedestal: 0xb00 #Pedestal voltage during measurement.
  input: acdc60/Raw_testData_ACC1_20240403_162735_b0_dll0x300.txt #When input is not empty, prefix and suffix are disabled.
  prefix: testData/acdc60_20240315_sin5ch_ #Final file name: prefix_(chnum)_suffix
  suffix: "" #_20220817_052515_b0.txt