
#RQ that are gobal to each event, as opposed to on a channel-to-channel basis
global:
  hpos: float #horiz position
  vpos: float #vertical position
  n_clusters: float #number of clusters (particles) in the event
  sys_time: int #320 MHz counter synchronous with 40 MHz sampling clock
  wr_time: int #250 MHz counter PLLd from 100 MHz output of WR ZEN
  filename: string #name of the file the event came from
  file_time: float #timestamp unix epoch from filename 
  evt_count: int #event index in the file it came from
  pps: float #1 Hz counter pulse-per-second from WR ZEN
  first_peak: float #times in ns of first pulse hitting readout
  wr_phi: float #phase from fitting sin(omega*t - phi)
  wr_freq: float #the WR 250 MHz frequency, in case it is not fixed
  max_ch: float #channel with the maximum amplitude
  start_cap: int #left bound of the trigger octant, from 0 to 255
  error_codes: array_int #a list of error codes for the event that indicate why it failed to reconstruct
  total_charge: float #add unit later, total charge in the event from reconstructable waveforms

#channel specific reduced quantities, which will have a key
#like "ch3_"+reduced_quantity_name. References the strip-number
#corrected channel number, not the original raw data chip channel
channel:
  baseline: float #mV, baseline of the channel
  std: float #mV, standard deviation of the baseline on the channel
  max: float #mV, maximum amplitude of the channel
  min: float #mV, minimum amplitude of the channel
  is_hit: int #0 or 1, whether the channel has enough amplitude to consider for reconstruction
  peak_times: array_float #only if is_hit, times in ns of the peaks in the channel
